-- Delete reference in GJBJOBS
DELETE FROM GJBJOBS where GJBJOBS_NAME in ('GYRRUBY')
/
commit;
/

-- Insert Job into GJBJOBS
INSERT INTO GJBJOBS ( GJBJOBS_NAME, GJBJOBS_TITLE, GJBJOBS_ACTIVITY_DATE, GJBJOBS_SYSI_CODE,
GJBJOBS_JOB_TYPE_IND, GJBJOBS_DESC, GJBJOBS_COMMAND_NAME, GJBJOBS_PRNT_FORM, GJBJOBS_PRNT_CODE,
GJBJOBS_LINE_COUNT, GJBJOBS_VALIDATION ) VALUES ( 'GYRRUBY', 'BannerJobsub Ruby Example', sysdate,
'N', 'C', 'BannerJobsub Ruby Example', NULL, NULL, NULL, 55, NULL)
/

commit;
/

-- Insert of Parameter Definition to GJBPDEF
DELETE FROM GJBPDEF where GJBPDEF_JOB in ('GYRRUBY')
/

INSERT INTO GJBPDEF ( GJBPDEF_JOB, GJBPDEF_NUMBER, GJBPDEF_DESC, GJBPDEF_LENGTH, GJBPDEF_TYPE_IND,
GJBPDEF_OPTIONAL_IND, GJBPDEF_SINGLE_IND, GJBPDEF_ACTIVITY_DATE, GJBPDEF_LOW_RANGE,
GJBPDEF_HIGH_RANGE, GJBPDEF_HELP_TEXT, GJBPDEF_VALIDATION,
GJBPDEF_LIST_VALUES ) VALUES ( 'GYRRUBY', '01', 'Start Date:', 11, 'D', 'R', 'S', sysdate
, NULL, NULL, 'Enter Term Code. Click arrow for values.', NULL, 'STVTERM')
/

INSERT INTO GJBPDEF ( GJBPDEF_JOB, GJBPDEF_NUMBER, GJBPDEF_DESC, GJBPDEF_LENGTH, GJBPDEF_TYPE_IND,
GJBPDEF_OPTIONAL_IND, GJBPDEF_SINGLE_IND, GJBPDEF_ACTIVITY_DATE, GJBPDEF_LOW_RANGE,
GJBPDEF_HIGH_RANGE, GJBPDEF_HELP_TEXT, GJBPDEF_VALIDATION,
GJBPDEF_LIST_VALUES ) VALUES ( 'GYRRUBY', '02', 'End Date:', 11, 'D', 'R', 'S', sysdate
, NULL, NULL, 'Level: [UG/GR/%]', NULL, NULL)
/

commit;
/

-- Insert Default parameter in GJBPDFT
DELETE FROM GJBPDFT where GJBPDFT_JOB in ('GYRRUBY')
/

INSERT INTO GJBPDFT ( GJBPDFT_JOB, GJBPDFT_NUMBER, GJBPDFT_ACTIVITY_DATE, GJBPDFT_USER_ID,
GJBPDFT_VALUE, GJBPDFT_JPRM_CODE ) VALUES ('GYRRUBY', '01',  sysdate, NULL, '23-JUN-1980', NULL)
/
INSERT INTO GJBPDFT ( GJBPDFT_JOB, GJBPDFT_NUMBER, GJBPDFT_ACTIVITY_DATE, GJBPDFT_USER_ID,
GJBPDFT_VALUE, GJBPDFT_JPRM_CODE ) VALUES ('GYRRUBY', '02',  sysdate, NULL, '23-JUN-1980', NULL)
/

commit;
/

-- Insert of reference in GUBOBJS
DELETE FROM GUBOBJS WHERE GUBOBJS_NAME = 'GYRRUBY';

INSERT INTO GUBOBJS (GUBOBJS_NAME, GUBOBJS_DESC, GUBOBJS_OBJT_CODE, GUBOBJS_SYSI_CODE,GUBOBJS_USER_ID,
GUBOBJS_ACTIVITY_DATE, GUBOBJS_HELP_IND, GUBOBJS_EXTRACT_ENABLED_IND)
VALUES  ('GYRRUBY', 'BannerJobsub Ruby Example','JOBS', 'G', 'LOCAL', SYSDATE, 'N', 'N');

commit;
/
